{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"items_powerbi\",\"killed_powerbi\",\"matches_powerbi\",\"players_powerbi\",\"teamfights_powerbi\",\"abilities_powerbi\",\"ability_names_powerbi\",\"item_names_powerbi\",\"killee_names_powerbi\",\"heroes_powerbi\",\"roles\",\"picks_bans\",\"players_matches\",\"Characters\",\"Sheet3\",\"hero_abils\",\"hero_scrape\",\"Characters 2\",\"players_final_items\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "extendedProperties": [
      {
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "type": "json",
        "value": {
          "name": "Config-01",
          "autoNaming": 1,
          "autoScan": 127,
          "dateAvailable": true,
          "dateEnabled": true,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "defaults": {
            "firstDayOfWeek": 1
          },
          "description": "Standard gregorian calendar",
          "exceptTablesColumns": [],
          "holidaysAvailable": true,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 0,
          "holidaysEnabled": false,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 0,
          "isCurrent": false,
          "isCustom": false,
          "isoCountry": "US",
          "onlyTablesColumns": [],
          "targetMeasures": [],
          "templateUri": "file:///C:/Users/jemma/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_5cc515a0-3835-4aa1-8163-14c3004c9c67",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "match_id",
        "fromTable": "teamfights_powerbi",
        "toColumn": "match_id",
        "toTable": "matches_powerbi"
      },
      {
        "name": "AutoDetected_e65ff684-f717-4108-ab38-9bf36871816c",
        "fromColumn": "killee_id",
        "fromTable": "killed_powerbi",
        "toColumn": "killee_id",
        "toTable": "killee_names_powerbi"
      },
      {
        "name": "7e4586e2-4722-4c39-b7be-71bd0ce48895",
        "fromColumn": "ability_id",
        "fromTable": "abilities_powerbi",
        "toColumn": "row_num",
        "toTable": "ability_names_powerbi"
      },
      {
        "name": "AutoDetected_81af04bd-1f64-48c2-abed-c1ba42c3a57f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "match_id",
        "fromTable": "picks_bans",
        "toCardinality": "many",
        "toColumn": "match_id",
        "toTable": "matches_powerbi"
      },
      {
        "name": "bbb17833-a02a-4f28-8fac-301db9c6969e",
        "fromColumn": "hero_id",
        "fromTable": "picks_bans",
        "toColumn": "id",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "7a932bb1-58e0-4600-bff7-cda468412d24",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "hero_id",
        "fromTable": "roles",
        "toColumn": "id",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "e87c967e-5429-4b3d-a680-798a7b561c98",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "secondary_key",
        "fromTable": "players_powerbi",
        "toColumn": "primary_key",
        "toTable": "teamfights_powerbi"
      },
      {
        "name": "457aad65-6e99-477a-b202-e123cc9fa413",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "primary_key",
        "fromTable": "items_powerbi",
        "toColumn": "primary_key",
        "toTable": "players_powerbi"
      },
      {
        "name": "a96785f8-f714-4ae5-809a-faa5210f3d6c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "primary_key",
        "fromTable": "abilities_powerbi",
        "toColumn": "primary_key",
        "toTable": "players_powerbi"
      },
      {
        "name": "d09292a5-6fa2-4836-a082-0fcd9cd52500",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "primary_key",
        "fromTable": "killed_powerbi",
        "toColumn": "primary_key",
        "toTable": "players_powerbi"
      },
      {
        "name": "0ec9ab6f-3a89-4af8-bfc0-a746b85a268f",
        "fromColumn": "start_time_date",
        "fromTable": "matches_powerbi",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "ada96f61-1791-4d85-9367-80bde1a42317",
        "fromColumn": "hero_id",
        "fromTable": "players_matches",
        "toColumn": "id",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "1144a091-7671-4d1a-bc62-4862adc4ed9e",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "names",
        "fromTable": "Characters",
        "toColumn": "localized_name",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "7de4ecd4-54ab-4934-ac04-aeab1366f215",
        "fromColumn": "hero_name",
        "fromTable": "hero_abils",
        "toColumn": "localized_name",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "c7b279a0-bdb7-42bb-b30d-193e6c2902a4",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "char_name",
        "fromTable": "hero_scrape",
        "toColumn": "localized_name",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "AutoDetected_6726455c-d828-4411-a5f8-af6cc5259d0c",
        "fromColumn": "names",
        "fromTable": "Sheet3",
        "toColumn": "names",
        "toTable": "Characters 2"
      },
      {
        "name": "AutoDetected_f37fc9be-22e1-40f8-b47e-eb7d5b65783a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "names",
        "fromTable": "Characters 2",
        "isActive": false,
        "toColumn": "localized_name",
        "toTable": "heroes_powerbi"
      },
      {
        "name": "b49b2ae7-2609-4711-81b2-65f53b498f2a",
        "fromColumn": "match_id",
        "fromTable": "players_matches",
        "toColumn": "match_id",
        "toTable": "matches_powerbi"
      },
      {
        "name": "cc114be8-e3fd-446c-8ecb-262e610240bd",
        "fromColumn": "item",
        "fromTable": "players_final_items",
        "toColumn": "item_id",
        "toTable": "item_names_powerbi"
      },
      {
        "name": "897b8c5f-6e6f-4e98-9539-2c55a03f3d12",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "primary_key",
        "fromTable": "players_final_items",
        "toColumn": "primary_key",
        "toTable": "players_matches"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "items_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f12c526-be8f-4ddb-8b40-e95ce8b86a8d",
            "sourceColumn": "match_id",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "607cbbf7-205f-473a-9c6e-b384dc7a699c",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f337d500-9db6-4ddd-8985-e690c9921de0",
            "sourceColumn": "account_id",
            "summarizeBy": "sum"
          },
          {
            "name": "hero_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3dec9597-47c5-42da-bd37-5c2f05510937",
            "sourceColumn": "hero_id",
            "summarizeBy": "sum"
          },
          {
            "name": "player_slot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf008ff1-bef2-4d35-87f6-d7a8cc3457d6",
            "sourceColumn": "player_slot",
            "summarizeBy": "sum"
          },
          {
            "name": "secondary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62c4ecfb-837c-4b8c-987c-8099011df28e",
            "sourceColumn": "secondary_key",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "e97244f7-076d-42cf-a032-63fa189541f2",
        "partitions": [
          {
            "name": "items_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    players_matches_Table = dota2_Schema{[Name=\"players_matches\",Kind=\"Table\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(players_matches_Table, \"secondary_key\", each [match_id] & \"-\" & [hero_id])",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "killed_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03e3a099-682e-4c97-b184-419796fa84b1",
            "sourceColumn": "match_id",
            "summarizeBy": "sum"
          },
          {
            "name": "fight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c54ba09-3425-4a84-aa07-73b11b510128",
            "sourceColumn": "fight",
            "summarizeBy": "sum"
          },
          {
            "name": "player_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fe198c8-e804-4d8d-a908-80c5d3542569",
            "sourceColumn": "player_num",
            "summarizeBy": "sum"
          },
          {
            "name": "killee_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "589785b9-0da6-4f4a-81d5-69a65497d009",
            "sourceColumn": "killee_id",
            "summarizeBy": "none"
          },
          {
            "name": "kills",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a6529df-ef8f-497d-9659-353f2e927ed4",
            "sourceColumn": "kills",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5c3a932-79c8-4aff-925f-a16e8d1aea21",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "784173e5-8136-47ff-ae74-83b46d081e03",
        "partitions": [
          {
            "name": "killed_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    killed_powerbi_View = dota2_Schema{[Name=\"killed_powerbi\",Kind=\"View\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(killed_powerbi_View, \"Custom\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([fight]), 2, \"0\") & \"_\" & Text.From([player_num])),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Custom\", \"primary_key\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "matches_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1df44f7e-2e23-4b60-b64a-0738abd8b5a0",
            "sourceColumn": "match_id",
            "summarizeBy": "none"
          },
          {
            "name": "radiant_win",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e3d372ff-f2cc-4cae-97e9-750a45ca6d09",
            "sourceColumn": "radiant_win",
            "summarizeBy": "none"
          },
          {
            "name": "start_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "912bbb18-611d-4689-b5c8-ad3e434184a2",
            "sourceColumn": "start_time",
            "summarizeBy": "none"
          },
          {
            "name": "duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb66e9be-600d-4c67-8cce-1461f9231e50",
            "sourceColumn": "duration",
            "summarizeBy": "sum"
          },
          {
            "name": "tower_status_radiant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "326c57d8-f081-402d-9073-25391e7b433c",
            "sourceColumn": "tower_status_radiant",
            "summarizeBy": "sum"
          },
          {
            "name": "tower_status_dire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63ef64f6-0a62-4a85-8446-017e50c860a5",
            "sourceColumn": "tower_status_dire",
            "summarizeBy": "sum"
          },
          {
            "name": "barracks_status_radiant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12145da0-6401-4888-b797-96e2843faaf2",
            "sourceColumn": "barracks_status_radiant",
            "summarizeBy": "sum"
          },
          {
            "name": "barracks_status_dire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "57d53c3f-dbc4-49e2-898b-f5472570c5de",
            "sourceColumn": "barracks_status_dire",
            "summarizeBy": "sum"
          },
          {
            "name": "cluster",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e53b21c1-e9f8-4c29-b1fe-ad343d5a04b6",
            "sourceColumn": "cluster",
            "summarizeBy": "sum"
          },
          {
            "name": "first_blood_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "658bbd7d-3624-40bf-830c-b3b527c39162",
            "sourceColumn": "first_blood_time",
            "summarizeBy": "sum"
          },
          {
            "name": "leagueid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "298f1b13-3e55-4d9d-8e05-b27ecb2f8934",
            "sourceColumn": "leagueid",
            "summarizeBy": "sum"
          },
          {
            "name": "game_mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7136d10f-3a46-497c-8d66-3ec9401a6a78",
            "sourceColumn": "game_mode",
            "summarizeBy": "sum"
          },
          {
            "name": "radiant_team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b79c450c-c112-45c2-9a88-6cec7c8bfbaf",
            "sourceColumn": "radiant_team_id",
            "summarizeBy": "sum"
          },
          {
            "name": "dire_team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1c333647-4822-4e0f-aef0-78b8cf7fae86",
            "sourceColumn": "dire_team_id",
            "summarizeBy": "sum"
          },
          {
            "name": "radiant_team_complete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e23a6e3-b836-492b-90f7-d0d9d844dc94",
            "sourceColumn": "radiant_team_complete",
            "summarizeBy": "sum"
          },
          {
            "name": "dire_team_complete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a2ee7c1a-4e06-4acf-b8bc-33cdd6194d05",
            "sourceColumn": "dire_team_complete",
            "summarizeBy": "sum"
          },
          {
            "name": "radiant_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c310fcbd-4717-414a-a3bb-25c271e1d739",
            "sourceColumn": "radiant_score",
            "summarizeBy": "sum"
          },
          {
            "name": "dire_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "adf4c8fc-a234-4a65-b6f7-a66432640af5",
            "sourceColumn": "dire_score",
            "summarizeBy": "sum"
          },
          {
            "name": "series_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e9d96da5-00b8-4bd1-8ddc-cc4cb5117ae6",
            "sourceColumn": "series_id",
            "summarizeBy": "sum"
          },
          {
            "name": "series_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "415f6e07-f0bf-41a3-98c1-2871ec903f37",
            "sourceColumn": "series_type",
            "summarizeBy": "sum"
          },
          {
            "name": "patch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25947e74-945b-4c9b-92e4-fb93a304bc32",
            "sourceColumn": "patch",
            "summarizeBy": "sum"
          },
          {
            "name": "start_time_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "300ef1b1-58f5-4850-b253-ad3fe98f0899",
            "sourceColumn": "start_time_date",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "a8887685-29fc-4bc3-a272-7e851b26a343",
        "partitions": [
          {
            "name": "matches_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    matches_powerbi_View = dota2_Schema{[Name=\"matches_powerbi\",Kind=\"View\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(matches_powerbi_View, \"Custom\", each [start_time]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Custom\", \"start_time_date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"start_time_date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "players_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c35badd-2f46-40b9-a95d-9e5c3c297256",
            "sourceColumn": "match_id",
            "summarizeBy": "sum"
          },
          {
            "name": "fight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5435d5c4-6729-4c95-9752-95f149da041e",
            "sourceColumn": "fight",
            "summarizeBy": "sum"
          },
          {
            "name": "player_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d9285c5-50b5-46d8-a63e-df8c289ab888",
            "sourceColumn": "player_num",
            "summarizeBy": "sum"
          },
          {
            "name": "deaths_pos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80922621-a57e-49c6-bb09-3f60037353ea",
            "sourceColumn": "deaths_pos",
            "summarizeBy": "none"
          },
          {
            "name": "ability_targets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8d54667-c274-400e-908b-9ed75b781995",
            "sourceColumn": "ability_targets",
            "summarizeBy": "none"
          },
          {
            "name": "deaths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e8dc24b-3ac1-4fe9-a999-7fbb0da22996",
            "sourceColumn": "deaths",
            "summarizeBy": "sum"
          },
          {
            "name": "buybacks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37749fa0-518c-4f13-ac6d-bd1fa0260702",
            "sourceColumn": "buybacks",
            "summarizeBy": "sum"
          },
          {
            "name": "damage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1e8e9936-6147-47a0-89fe-5dca5bb5beeb",
            "sourceColumn": "damage",
            "summarizeBy": "sum"
          },
          {
            "name": "healing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bdf51c5-1809-4530-9a21-60c4db1c14d5",
            "sourceColumn": "healing",
            "summarizeBy": "sum"
          },
          {
            "name": "gold_delta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46e03b2e-4626-44f8-b9ed-2e1a42943ae7",
            "sourceColumn": "gold_delta",
            "summarizeBy": "sum"
          },
          {
            "name": "xp_delta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbcd47d1-b84c-43ab-b870-f2ae34ef9d35",
            "sourceColumn": "xp_delta",
            "summarizeBy": "sum"
          },
          {
            "name": "xp_start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c4fa2439-b2a6-4072-bcbc-ba1fad166bd9",
            "sourceColumn": "xp_start",
            "summarizeBy": "sum"
          },
          {
            "name": "xp_end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bfcc961a-017f-4a0d-9490-a208ef586ca1",
            "sourceColumn": "xp_end",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05c18abb-a7e1-4c67-a155-278636306739",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          },
          {
            "name": "secondary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f46ab3-44cd-46f1-a994-5e8770e29049",
            "sourceColumn": "secondary_key",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "06c3784e-5bb5-4586-b066-dbfdc1c86185",
        "partitions": [
          {
            "name": "players_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    players_powerbi_View = dota2_Schema{[Name=\"players_powerbi\",Kind=\"View\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(players_powerbi_View, \"primary_key\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([fight]), 2, \"0\") & \"_\" & Text.From([player_num])),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"secondary_key\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([fight]), 2, \"0\"))",
                "in",
                "    #\"Added Custom1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "teamfights_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1aa82d90-a479-4ad5-91f4-387fcd18a234",
            "sourceColumn": "match_id",
            "summarizeBy": "none"
          },
          {
            "name": "fight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "526ac2b5-7b44-4d23-80b0-5b254c7e7b23",
            "sourceColumn": "fight",
            "summarizeBy": "sum"
          },
          {
            "name": "fight_start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "beec290e-796e-4594-880f-d4d00d230044",
            "sourceColumn": "fight_start",
            "summarizeBy": "sum"
          },
          {
            "name": "fight_end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f9f88d1-b649-42a1-bc01-137ee644fe16",
            "sourceColumn": "fight_end",
            "summarizeBy": "sum"
          },
          {
            "name": "last_death",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "851db093-56c7-4518-8f7a-1aa92d371370",
            "sourceColumn": "last_death",
            "summarizeBy": "sum"
          },
          {
            "name": "deaths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35dcd15b-e0b4-4d40-89c6-6fcb3a90b0ad",
            "sourceColumn": "deaths",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63f74221-23cc-48af-8269-d8b6af77b625",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "b36ce3b9-afaf-4b79-bbc2-87abc10be1d8",
        "partitions": [
          {
            "name": "teamfights_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    teamfights_powerbi_View = dota2_Schema{[Name=\"teamfights_powerbi\",Kind=\"View\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(teamfights_powerbi_View, \"primary_key\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([fight]), 2, \"0\"))",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "abilities_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04f4c9f8-60d1-4f90-9730-1078e99953f3",
            "sourceColumn": "match_id",
            "summarizeBy": "sum"
          },
          {
            "name": "fight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5ca62ff-0e13-46fc-a4b6-aae462de13bb",
            "sourceColumn": "fight",
            "summarizeBy": "sum"
          },
          {
            "name": "player_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f660df06-b4da-41f0-9d65-a82a765b6634",
            "sourceColumn": "player_num",
            "summarizeBy": "sum"
          },
          {
            "name": "ability_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e872dae-24ca-4961-b034-2448b8e05199",
            "sourceColumn": "ability_id",
            "summarizeBy": "none"
          },
          {
            "name": "uses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e7cb5168-7a9e-4230-9831-3d5b19f0075e",
            "sourceColumn": "uses",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af40cafa-d1b8-484b-8d41-e66f06a0ee05",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "20109395-f980-44d7-81a5-9290b51f5ba6",
        "partitions": [
          {
            "name": "abilities_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    abilities_powerbi_Table = dota2_Schema{[Name=\"abilities_powerbi\",Kind=\"Table\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(abilities_powerbi_Table, \"Custom\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([fight]), 2, \"0\") & \"_\" & Text.From([player_num])),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Custom\", \"primary_key\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ability_names_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fbc80fe-b3f3-4038-ad34-b3860215faab",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "row_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0fb6f83c-23d7-4f8d-8f60-99589c9ed84f",
            "sourceColumn": "row_num",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "3e26d393-eef6-4564-9886-e1424de993d5",
        "partitions": [
          {
            "name": "ability_names_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    ability_names_powerbi_Table = dota2_Schema{[Name=\"ability_names_powerbi\",Kind=\"Table\"]}[Data]",
                "in",
                "    ability_names_powerbi_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "item_names_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "item_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b988e20c-d263-4f54-93ae-c2fed7f489e3",
            "sourceColumn": "item_id",
            "summarizeBy": "none"
          },
          {
            "name": "item_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "437984d7-09b0-45fd-90c9-edb58138ca28",
            "sourceColumn": "item_name",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "96e9f718-d92c-4af0-9cb3-c00a39ca8985",
        "partitions": [
          {
            "name": "item_names_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    item_names_powerbi_Table = dota2_Schema{[Name=\"item_names_powerbi\",Kind=\"Table\"]}[Data]",
                "in",
                "    item_names_powerbi_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "killee_names_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "killee_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f07739cf-5f8b-4741-b5a7-e694413c5806",
            "sourceColumn": "killee_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8c7f736-c741-4fe9-bb7d-ac72a224dc53",
            "sourceColumn": "name",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "f4e6e124-7b45-4b20-ba33-94f6cd9159d0",
        "partitions": [
          {
            "name": "killee_names_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    killee_names_powerbi_Table = dota2_Schema{[Name=\"killee_names_powerbi\",Kind=\"Table\"]}[Data]",
                "in",
                "    killee_names_powerbi_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "heroes_powerbi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "082d1ee8-148e-4980-aba6-09a9e8e6cf28",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1288b00-eb90-4e1a-820f-880cf6024047",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "localized_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31f8763a-748e-4b58-8049-61e5fa31696d",
            "sourceColumn": "localized_name",
            "summarizeBy": "none"
          },
          {
            "name": "primary_attr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b2a1e52-060c-45db-ae85-44e5913b60f7",
            "sourceColumn": "primary_attr",
            "summarizeBy": "none"
          },
          {
            "name": "attack_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fbb83e1-5722-4a90-b7a7-9867786e9070",
            "sourceColumn": "attack_type",
            "summarizeBy": "none"
          },
          {
            "name": "legs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d44a362a-d046-4844-8f28-736bf0ca9217",
            "sourceColumn": "legs",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "a58bfc72-5325-4e7a-96be-51b64329228d",
        "partitions": [
          {
            "name": "heroes_powerbi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    heroes_powerbi_View = dota2_Schema{[Name=\"heroes_powerbi\",Kind=\"View\"]}[Data]",
                "in",
                "    heroes_powerbi_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "roles",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "role",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "056517d5-0965-4b91-8408-3fe5a2c437fe",
            "sourceColumn": "role",
            "summarizeBy": "none"
          },
          {
            "name": "hero_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5db9f641-d58a-471b-b03e-6c2e16eeac29",
            "sourceColumn": "hero_id",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "6b638360-e9aa-403d-92e3-84fe774bf429",
        "partitions": [
          {
            "name": "roles",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    roles_Table = dota2_Schema{[Name=\"roles\",Kind=\"Table\"]}[Data]",
                "in",
                "    roles_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "picks_bans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "is_pick",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6666904e-1f52-4ea0-90f5-2c01c1b865cd",
            "sourceColumn": "is_pick",
            "summarizeBy": "none"
          },
          {
            "name": "hero_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6cabf8d-3b1d-4563-b54c-607f54fa357b",
            "sourceColumn": "hero_id",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "124201b0-3e35-49e6-bb6a-6779ae25f274",
            "sourceColumn": "team",
            "summarizeBy": "sum"
          },
          {
            "name": "order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc7fbc43-d9ca-4b86-9c68-9dd34761a049",
            "sourceColumn": "order",
            "summarizeBy": "sum"
          },
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7d80402-7b8e-417a-bfa2-1f98547568c8",
            "sourceColumn": "match_id",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "58ec913d-bbaa-45bd-b64e-52076f18e22e",
        "measures": [
          {
            "name": "Banned",
            "expression": "CALCULATE(DISTINCTCOUNT(picks_bans[match_id]), picks_bans[is_pick] = FALSE())",
            "formatString": "0",
            "lineageTag": "8b7beb0d-e6ca-4939-af38-5ed2e1ae054f"
          },
          {
            "name": "Picked",
            "expression": "CALCULATE(DISTINCTCOUNT(picks_bans[match_id]), picks_bans[is_pick] = TRUE())",
            "formatString": "0",
            "lineageTag": "9c11069e-b8cb-46a8-ae16-ea383102580e"
          },
          {
            "name": "Ban_perc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Banned] / CALCULATE(DISTINCTCOUNT(players_matches[match_id]), ALL(players_matches))",
            "lineageTag": "a95d7ce9-f89e-4ad2-ba13-579ab66b358e"
          },
          {
            "name": "Universal_Total",
            "expression": "CALCULATE(DISTINCTCOUNT(matches_powerbi[match_id]), ALL(matches_powerbi))",
            "formatString": "0",
            "lineageTag": "c2ff496a-a3f1-434c-9bb0-f29d14a86943"
          },
          {
            "name": "test",
            "expression": "CALCULATE(DISTINCTCOUNT(players_matches[match_id]), ALL(players_matches))",
            "formatString": "0",
            "lineageTag": "61304276-2f4e-42d6-ac01-b5ab28368ede"
          },
          {
            "name": "WinRate_to_BanRate",
            "expression": "[Win_Ratio] * (1- picks_bans[Ban_perc])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "92cffe8f-30b5-47da-b799-a671724df95c"
          },
          {
            "name": "Availability",
            "expression": "1- picks_bans[Ban_perc]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a8e0b4d3-c0a8-4fe8-8890-d38e0d68d5d1"
          },
          {
            "name": "Ban_Time",
            "expression": [
              "",
              "VAR TotalMatches =",
              "    CALCULATE(",
              "        DISTINCTCOUNT(players_matches[match_id]),",
              "        ALL(players_matches)",
              "    )",
              "",
              "VAR MatchesInPeriod =",
              "    SWITCH(",
              "        TRUE(),",
              "        ISFILTERED('Date'[Date]),",
              "            CALCULATE(",
              "                DISTINCTCOUNT(players_matches[match_id]),",
              "                ALL(players_matches),",
              "                FILTER(",
              "                    ALL('Date'),",
              "                    'Date'[Date] <= MAX('Date'[Date])",
              "                )",
              "            ),",
              "        ISFILTERED('Date'[Month]),",
              "            CALCULATE(",
              "                DISTINCTCOUNT(players_matches[match_id]),",
              "                ALL(players_matches),",
              "                DATESMTD('Date'[Date])",
              "            ),",
              "        ISFILTERED('Date'[Year]),",
              "            CALCULATE(",
              "                DISTINCTCOUNT(players_matches[match_id]),",
              "                ALL(players_matches),",
              "                DATESYTD('Date'[Date])",
              "            )",
              "    )",
              "",
              "RETURN",
              "    IF(TotalMatches = 0, BLANK(), [Banned] / MatchesInPeriod)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f626e58d-5a97-428c-9fde-6737975ebe14"
          },
          {
            "name": "Available_Time",
            "expression": "1-[Ban_Time]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ea8652ac-4773-4c85-a70e-e4525b2f07ef"
          }
        ],
        "partitions": [
          {
            "name": "picks_bans",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    picks_bans_Table = dota2_Schema{[Name=\"picks_bans\",Kind=\"Table\"]}[Data]",
                "in",
                "    picks_bans_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "e434b1ef-6e9e-4a1a-83fb-a8014a1bd4b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9d01a026-c455-4a6b-9c89-24cd0c115cd7",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e3ca367d-666c-4068-9a50-58bc65b896aa",
            "sourceColumn": "[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "561e1d80-f7bd-4821-ba59-7b56351fc37e",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8404cc3-5ffe-4295-a2ff-3cc8538db260",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "74125d63-374f-4bef-89d8-10503c00246d",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "534bd192-7577-4767-9c08-4ab0a5a43421",
            "sourceColumn": "[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5aaba5ed-acee-4225-8a88-14005e71c896",
            "sortByColumn": "Month Number",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "27e00c48-4d9c-4356-a490-483e8c880900",
            "sourceColumn": "[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3d9bdbc7-c2cc-461b-a2af-3994c589c7d6",
            "sourceColumn": "[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "38771151-34f1-4e3e-a50b-8d8d0bd2615c",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "30956edc-e49f-4975-b359-fbe38574105b",
            "sourceColumn": "[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a30ed4e4-ecfa-48f5-9af2-a546872754d7",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "227ba980-a22c-48f6-94e4-88a859326f43",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "54346117-a7ee-4608-84a8-5946926c1861",
                "ordinal": 2
              }
            ],
            "lineageTag": "7c988e12-e71b-4951-b575-7887e3d449bb"
          }
        ],
        "isHidden": true,
        "lineageTag": "f5f6742e-7906-498e-98e3-c389f74efd54",
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstDayOfWeek = 1",
                "----------------------------------------",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'matches_powerbi'[start_time] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'matches_powerbi'[start_time] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "        VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "        VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'matches_powerbi'[start_time] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __QuarterNumber = QUARTER ( __Date )",
                "        VAR __YearQuarterNumber = CONVERT ( __YearNumber * 4 + __QuarterNumber - 1, INTEGER )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        RETURN ROW ( ",
                "            \"Year\", __YearNumber,",
                "            \"Year Quarter Number\", __YearQuarterNumber,",
                "            \"Year Quarter\", FORMAT ( __QuarterNumber, \"\\Q0\" ) & \"-\" & FORMAT ( __YearNumber, \"0000\" ),",
                "            \"Quarter\", FORMAT( __QuarterNumber, \"\\Q0\" ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Month Number\", __MonthNumber,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "b703c1a6-208b-4da3-9198-8d76c226c385",
            "sourceColumn": "DateAutoTemplate[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9b920eeb-93fe-48b7-b057-e06a2471ab8b",
            "sourceColumn": "DateAutoTemplate[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6a5085c6-8f29-4301-ac88-a903ad9bbda8",
            "sourceColumn": "DateAutoTemplate[Year Quarter Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Quarter",
            "dataCategory": "Quarters",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2e5fe4d4-7af4-44ac-a64a-0b14a720192f",
            "sortByColumn": "Year Quarter Number",
            "sourceColumn": "DateAutoTemplate[Year Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "dataCategory": "QuarterOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0c086296-ec7a-449b-863c-64152d635156",
            "sourceColumn": "DateAutoTemplate[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month",
            "dataCategory": "Months",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0f326f7b-7d94-4642-8da6-2ae058e50e3d",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Months",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "94df8300-b7fb-4a4c-aea1-1c767e066e69",
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "dataCategory": "MonthOfYear",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "13165266-db1d-410a-8e7a-99a926dc6734",
            "sortByColumn": "Month Number",
            "sourceColumn": "DateAutoTemplate[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6dd7739b-d284-4dea-8cfd-6d8e1ffde35e",
            "sourceColumn": "DateAutoTemplate[Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "005fb4dc-deb5-4160-8cc5-ff4f27068ce8",
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ],
            "dataCategory": "DayOfWeek",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1cd91f36-f09c-4b54-86fe-8749e02116e9",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateWithTransactions",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ],
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2b8b7a48-9da7-464a-9c24-168e985ef86c",
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Calendar",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "300eb4f7-f09e-4046-be83-4c493d9f74c2",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Year Month",
                "lineageTag": "e7f678d5-4d8d-4625-a7ef-db9802fcac21",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "60124b7c-6966-4428-99bb-0cded013c007",
                "ordinal": 2
              }
            ],
            "lineageTag": "87470f5d-d914-44e7-bedb-6866e776c8a7"
          }
        ],
        "lineageTag": "6d54d6f8-5e6e-4935-ab52-a5ff93db7f84",
        "measures": [
          {
            "name": "_ShowValueForDates",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ],
            "displayFolder": "Hidden Time Intelligence",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'matches_powerbi'[start_time] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "lineageTag": "cb35ad55-883f-4d90-ad8c-98ab4f090f44"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": "DateAutoTemplate",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "players_matches",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ffcff30-c409-4881-8033-17bf5a357a09",
            "sourceColumn": "match_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4c20ea8f-d293-415e-a4f1-ea06f0545a0d",
            "sourceColumn": "account_id",
            "summarizeBy": "sum"
          },
          {
            "name": "player_slot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb67f92d-9503-4bfa-af7c-a9eb23cb1c0d",
            "sourceColumn": "player_slot",
            "summarizeBy": "sum"
          },
          {
            "name": "hero_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d628dac-9c44-4487-9ce3-eb109c79ae94",
            "sourceColumn": "hero_id",
            "summarizeBy": "none"
          },
          {
            "name": "side",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(players_matches[player_slot] < 128, \"Radiant\", \"Dire\")",
            "isDataTypeInferred": true,
            "lineageTag": "f6b4c099-2770-4dc0-b986-8597bcd3e2ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "win",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(OR(AND(players_matches[side]=\"Radiant\", RELATED(matches_powerbi[radiant_win])=TRUE()), AND(players_matches[side]=\"Dire\", RELATED(matches_powerbi[radiant_win])=FALSE())), 1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e4155f52-9d94-40f9-ba62-5ae263633903",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb7d4610-bbf7-4b9d-907f-063b18490ac2",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          },
          {
            "name": "secondary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd67ede1-271f-4130-b109-403146f9e6d2",
            "sourceColumn": "secondary_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "43470b1c-981e-48ae-9ef6-987642846a71",
        "measures": [
          {
            "name": "Wins",
            "expression": "CALCULATE(SUM(players_matches[win]))",
            "formatString": "0",
            "lineageTag": "f492ff1b-4405-4e80-a918-61b5fd7d0af5"
          },
          {
            "name": "Total_Matches",
            "expression": "CALCULATE(DISTINCTCOUNT(players_matches[match_id]))",
            "formatString": "0",
            "lineageTag": "74ef0552-cacd-46ab-9a19-d9cabffa86d7"
          },
          {
            "name": "Losses",
            "expression": "[Total_Matches] - [Wins]",
            "formatString": "0",
            "lineageTag": "5afc2ecf-b6f3-4549-b555-e65f07770f3e"
          },
          {
            "name": "Win_Ratio",
            "expression": "[Wins] / [Total_Matches]",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "2a22bc9f-8f4a-4936-bc07-a163a1e42117"
          },
          {
            "name": "h2h_total_matches",
            "expression": [
              "",
              "VAR _char2 = ",
              "    SELECTEDVALUE('Characters 2'[names])",
              "VAR _char1 = ",
              "    SELECTEDVALUE('Characters'[names])",
              "VAR _id2 =",
              "    CALCULATE(MAX(heroes_powerbi[id]), USERELATIONSHIP(heroes_powerbi[localized_name], 'Characters 2'[names]), ALL(heroes_powerbi))",
              "VAR _id1 =",
              "    MAX(heroes_powerbi[id])",
              "VAR _char1_match_ids =",
              "    CALCULATETABLE(",
              "        DISTINCT(players_matches[match_id]),",
              "        players_matches[hero_id] = _id1",
              "    )",
              "",
              "VAR _char2_match_ids =",
              "    CALCULATETABLE(",
              "        DISTINCT(players_matches[match_id]),",
              "        players_matches[hero_id] = _id2,",
              "        ALL('Characters')  // Ignore the global active filter on 'Characters'",
              "    )",
              "",
              "VAR _char1_matches =",
              "    FILTER(",
              "        players_matches,",
              "        players_matches[match_id] IN _char1_match_ids",
              "    )",
              "",
              "VAR _char2_matches =",
              "    FILTER(",
              "        ALL(players_matches),  // Ignore any active filters",
              "        players_matches[match_id] IN _char2_match_ids",
              "    )",
              "",
              "VAR _table_intersect = ",
              "    INTERSECT(_char1_matches, _char2_matches)",
              "VAR _common_match_ids =",
              "    INTERSECT(_char1_match_ids, _char2_match_ids)",
              "",
              "VAR _different_sides_matches =",
              "    FILTER(",
              "        players_matches,",
              "        players_matches[match_id] IN _common_match_ids &&",
              "        CALCULATE(",
              "            DISTINCTCOUNT(players_matches[side]),",
              "            players_matches[match_id] = EARLIER(players_matches[match_id]),",
              "            players_matches[hero_id] = _id1 || players_matches[hero_id] = _id2",
              "        ) = 2",
              "    )",
              "",
              "RETURN",
              "    MAX(_different_sides_matches[match_id])"
            ],
            "lineageTag": "7ab15bde-c7b1-45c0-914b-871d054daf0a"
          }
        ],
        "partitions": [
          {
            "name": "players_matches",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database([BillingProject=\"dota-2-77927\"]),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    players_matches_Table = dota2_Schema{[Name=\"players_matches\",Kind=\"Table\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(players_matches_Table, \"secondary_key\", each Text.From([match_id]) & \"_\" & Text.PadStart(Text.From([hero_id]), 3, \"0\"))",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Characters",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06374edb-deca-4bba-8460-e617900e72bc",
            "sourceColumn": "names",
            "summarizeBy": "none"
          },
          {
            "name": "button_images",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e55abfb5-deab-4fa4-b081-703fd3bc3a84",
            "sourceColumn": "button_images",
            "summarizeBy": "none"
          },
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2ced9bf-7196-45b3-8d53-ef28251345dc",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "name_caps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "629e9800-d6ca-4930-ae48-6cc623284e7a",
            "sourceColumn": "name_caps",
            "summarizeBy": "none"
          },
          {
            "name": "video_resized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c50625e-d01c-46f9-a0de-f1aa9b0fb131",
            "sourceColumn": "video_resized",
            "summarizeBy": "none"
          },
          {
            "name": "_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9728b39d-5ed3-40e3-8d44-18423cd8692a",
            "sourceColumn": "_3",
            "summarizeBy": "none"
          },
          {
            "name": "_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29cf4c29-dd81-4d19-9ba4-38aebe9817a8",
            "sourceColumn": "_6",
            "summarizeBy": "none"
          },
          {
            "name": "_10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a763a35-9205-49e3-bd2b-cd56e79785b4",
            "sourceColumn": "_10",
            "summarizeBy": "none"
          },
          {
            "name": "_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "632fab5e-c1c2-45cc-b43a-989a1cca4574",
            "sourceColumn": "_14",
            "summarizeBy": "none"
          },
          {
            "name": "_18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d1b8966-7375-414c-84cb-744e16a90f90",
            "sourceColumn": "_18",
            "summarizeBy": "none"
          },
          {
            "name": "_21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b148db7c-69ae-4db7-ab5e-0efeb05b2029",
            "sourceColumn": "_21",
            "summarizeBy": "none"
          },
          {
            "name": "_25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e28f7dd-d456-44af-bece-f33f6380d0d8",
            "sourceColumn": "_25",
            "summarizeBy": "none"
          },
          {
            "name": "_29",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0159629a-5c80-432d-b1c8-bbd658d5e85f",
            "sourceColumn": "_29",
            "summarizeBy": "none"
          },
          {
            "name": "_33",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7a30dbb-f4db-43f5-adcd-5c560b695413",
            "sourceColumn": "_33",
            "summarizeBy": "none"
          },
          {
            "name": "_36",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26e6f464-8b44-40ad-8264-1c53f644dc9f",
            "sourceColumn": "_36",
            "summarizeBy": "none"
          },
          {
            "name": "_40",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c391301-90d8-4393-a1b5-e2df0a42d6dc",
            "sourceColumn": "_40",
            "summarizeBy": "none"
          },
          {
            "name": "_44",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ed70620-491d-41df-9986-0db0a2970a7c",
            "sourceColumn": "_44",
            "summarizeBy": "none"
          },
          {
            "name": "_48",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89c7c230-4545-4eb4-8208-ae7db804d932",
            "sourceColumn": "_48",
            "summarizeBy": "none"
          },
          {
            "name": "ability_1_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "080fa860-49be-4de7-ae56-797620667b0f",
            "sourceColumn": "ability_1_img",
            "summarizeBy": "none"
          },
          {
            "name": "ability_1_vid_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eefbeb6c-356b-4d9f-97c9-adb746f49e0d",
            "sourceColumn": "ability_1_vid_code",
            "summarizeBy": "none"
          },
          {
            "name": "_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62a3a673-7c38-4425-aea6-49023fe09027",
            "sourceColumn": "_2",
            "summarizeBy": "none"
          },
          {
            "name": "_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc34890-01b5-4f8a-9885-44503a3bdd70",
            "sourceColumn": "_4",
            "summarizeBy": "none"
          },
          {
            "name": "_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6ac3155-085b-45db-a317-d109e30acea2",
            "sourceColumn": "_5",
            "summarizeBy": "none"
          },
          {
            "name": "_7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "548bf003-a08a-42c5-9827-bc9eb246da36",
            "sourceColumn": "_7",
            "summarizeBy": "none"
          },
          {
            "name": "_8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "151f4e63-0351-4f5e-bf06-67b3f6cc23bb",
            "sourceColumn": "_8",
            "summarizeBy": "none"
          },
          {
            "name": "_9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90e834e5-bee8-4fa5-9961-bba91a13d31e",
            "sourceColumn": "_9",
            "summarizeBy": "none"
          },
          {
            "name": "_11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19e82175-4c81-4f16-92e5-0b9cfc2a772c",
            "sourceColumn": "_11",
            "summarizeBy": "none"
          },
          {
            "name": "_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d2b2240-f785-49b5-8096-03fc287713b7",
            "sourceColumn": "_12",
            "summarizeBy": "none"
          },
          {
            "name": "_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3af48e5f-e80b-49db-8b30-683fcb9b1b37",
            "sourceColumn": "_13",
            "summarizeBy": "none"
          },
          {
            "name": "_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3706450c-d9f9-4e05-9ef0-0d16e096a75f",
            "sourceColumn": "_15",
            "summarizeBy": "none"
          },
          {
            "name": "_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8cef71a-9d6c-4bd6-870a-c9a58baab850",
            "sourceColumn": "_16",
            "summarizeBy": "none"
          },
          {
            "name": "_17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fec6ad22-a0c0-4242-b5bc-56251f4d81a7",
            "sourceColumn": "_17",
            "summarizeBy": "none"
          },
          {
            "name": "_19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99639ec0-39fe-4164-a393-caedfc82d7d1",
            "sourceColumn": "_19",
            "summarizeBy": "none"
          },
          {
            "name": "_20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cf2668c-2ed8-4636-92d8-3c2c3d062ca6",
            "sourceColumn": "_20",
            "summarizeBy": "none"
          },
          {
            "name": "_22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "861cf740-dbda-4339-b4cd-17bdbee7fe53",
            "sourceColumn": "_22",
            "summarizeBy": "none"
          },
          {
            "name": "_23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09c22002-2dc1-4c81-b65a-68dfb4a4f6b9",
            "sourceColumn": "_23",
            "summarizeBy": "none"
          },
          {
            "name": "_24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0affdb4-57f7-4e2e-9137-74be2006a34e",
            "sourceColumn": "_24",
            "summarizeBy": "none"
          },
          {
            "name": "_26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a881c220-a236-4ebc-923c-29d686ed8d0f",
            "sourceColumn": "_26",
            "summarizeBy": "none"
          },
          {
            "name": "_27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88d4f0cc-d26c-44f7-9558-e9f00a6da832",
            "sourceColumn": "_27",
            "summarizeBy": "none"
          },
          {
            "name": "_28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4882195-6311-448c-8c95-c45438e232b4",
            "sourceColumn": "_28",
            "summarizeBy": "none"
          },
          {
            "name": "_30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcb78c44-f74f-49ba-9cc2-b2a0ae7097f3",
            "sourceColumn": "_30",
            "summarizeBy": "none"
          },
          {
            "name": "_31",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d299b568-0f8c-4c36-8bdd-da424284355a",
            "sourceColumn": "_31",
            "summarizeBy": "none"
          },
          {
            "name": "_32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b5b0d54-e13e-4c91-8d2c-96656d527220",
            "sourceColumn": "_32",
            "summarizeBy": "none"
          },
          {
            "name": "_34",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "918d872d-b762-4828-b87f-1aebdae588c9",
            "sourceColumn": "_34",
            "summarizeBy": "none"
          },
          {
            "name": "_35",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74706cdc-f35b-46ef-bd7c-95c9b4033c96",
            "sourceColumn": "_35",
            "summarizeBy": "none"
          },
          {
            "name": "_37",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58283da3-7a84-4a3b-b846-d8ddac842680",
            "sourceColumn": "_37",
            "summarizeBy": "none"
          },
          {
            "name": "_38",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2206c9f1-9527-4a7e-a542-fc98ef881b1c",
            "sourceColumn": "_38",
            "summarizeBy": "none"
          },
          {
            "name": "_39",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acbcfa9e-bf7b-45b0-b9e9-8483b59a5091",
            "sourceColumn": "_39",
            "summarizeBy": "none"
          },
          {
            "name": "_41",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96778c75-4bc1-416e-997c-3b185f944386",
            "sourceColumn": "_41",
            "summarizeBy": "none"
          },
          {
            "name": "_42",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b93b870f-a680-4be6-891f-2a6393bf60fd",
            "sourceColumn": "_42",
            "summarizeBy": "none"
          },
          {
            "name": "_43",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b21b11f-6220-466d-8869-cde24810b5b8",
            "sourceColumn": "_43",
            "summarizeBy": "none"
          },
          {
            "name": "_45",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81c5becc-be30-4e8e-a55e-169c6ed1a636",
            "sourceColumn": "_45",
            "summarizeBy": "none"
          },
          {
            "name": "_46",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d8be847-acf6-46b0-b92a-1860adea3644",
            "sourceColumn": "_46",
            "summarizeBy": "none"
          },
          {
            "name": "_47",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f977cd-59c2-4c3b-8b69-2ae32e89ada0",
            "sourceColumn": "_47",
            "summarizeBy": "none"
          },
          {
            "name": "_49",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26b13fdd-9690-49f3-8481-5ec8de11069f",
            "sourceColumn": "_49",
            "summarizeBy": "none"
          },
          {
            "name": "_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fd472f5-c4e0-48a6-b968-90c7ba622fad",
            "sourceColumn": "_50",
            "summarizeBy": "none"
          },
          {
            "name": "ab1_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bf2fb07-0b6a-437e-ae55-560ccb5ded37",
            "sourceColumn": "ab1_title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "10714272-ffed-47c4-acd9-5bcb17dbee50",
        "partitions": [
          {
            "name": "Characters",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1zLxE1yP648A_V_HPK0kZu2wDrG2vRDaf4A3UJzb9RPk/edit?usp=sharing\"),",
                "    Characters_Table = Source{[name=\"Characters\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Characters_Table, [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"ability_1_class_start\", \"ability_1_img_start\", \"ability_1_img_end\", \"ability_1_video_html_start\", \"ability_1_video_html_start_1\", \"ab1_class_start\", \"ab1_text_start\", \"\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sheet3",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c0c8aff-4307-481e-84fb-db14d36dafba",
            "sourceColumn": "names",
            "summarizeBy": "none"
          },
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84d1b296-b4c4-4427-a38b-9c26dfd77573",
            "sourceColumn": "Column1",
            "summarizeBy": "sum"
          },
          {
            "name": "ab_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c51cf5f-56be-40d4-bab2-ae5d2e3eccbe",
            "sourceColumn": "ab_title",
            "summarizeBy": "none"
          },
          {
            "name": "ab_text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31de6b53-2482-4249-9de2-26a9f1dcbd5b",
            "sourceColumn": "ab_text",
            "summarizeBy": "none"
          },
          {
            "name": "ab_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a19f228a-854e-477d-88b2-e18a9820b921",
            "sourceColumn": "ab_img",
            "summarizeBy": "none"
          },
          {
            "name": "ab_vid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce777a8-7d32-4c92-8d52-77b9b37ede96",
            "sourceColumn": "ab_vid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "888d5554-ab4b-43c6-a8aa-f370591fb288",
        "partitions": [
          {
            "name": "Sheet3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1zLxE1yP648A_V_HPK0kZu2wDrG2vRDaf4A3UJzb9RPk/edit?usp=sharing\"),",
                "    Sheet3_Table = Source{[name=\"Sheet3\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet3_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"names\", type text}, {\"\", Int64.Type}, {\"ab_title\", type text}, {\"ab_text\", type text}, {\"ab_img\", type text}, {\"ab_vid\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "hero_abils",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "hero_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14563ff6-8478-4013-a5cc-64cdd821b490",
            "sourceColumn": "hero_name",
            "summarizeBy": "none"
          },
          {
            "name": "abil_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91c6416f-b997-48c2-81d9-c7daeccba3f3",
            "sourceColumn": "abil_num",
            "summarizeBy": "sum"
          },
          {
            "name": "abil_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0311680c-36db-451f-8c86-38eae92df04d",
            "sourceColumn": "abil_name",
            "summarizeBy": "none"
          },
          {
            "name": "abil_text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2a81902-c28e-4bac-82ef-df2b1455f66b",
            "sourceColumn": "abil_text",
            "summarizeBy": "none"
          },
          {
            "name": "abil_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "975026eb-bcf4-4899-9a2f-b8c5fa5f7155",
            "sourceColumn": "abil_img",
            "summarizeBy": "none"
          },
          {
            "name": "abil_vid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2442b73-7931-4106-aa63-af3026a5b582",
            "sourceColumn": "abil_vid",
            "summarizeBy": "none"
          },
          {
            "name": "abil_vid_html",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38080467-f37e-4ab6-b376-791ec51c374d",
            "sourceColumn": "abil_vid_html",
            "summarizeBy": "none"
          },
          {
            "name": "abil_img_html",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec876255-736a-451e-bd53-a1bb33d29a77",
            "sourceColumn": "abil_img_html",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e8f7610b-3b0d-4a23-b5d6-415a547589a1",
        "partitions": [
          {
            "name": "hero_abils",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1JhQDKRX0o7GZH9CVEuSj8-r1oNx2XGYzfaTVH3tkCDI/edit?usp=sharing\"),",
                "    hero_abils_Table = Source{[name=\"hero_abils\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(hero_abils_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"hero_name\", type text}, {\"abil_num\", Int64.Type}, {\"abil_name\", type text}, {\"abil_text\", type text}, {\"abil_img\", type text}, {\"abil_vid\", type text}, {\"abil_vid_html\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "hero_scrape",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "char_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f87fead-9d8c-4e53-a3d3-9c5725cadec7",
            "sourceColumn": "char_name",
            "summarizeBy": "none"
          },
          {
            "name": "char_attr_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf78ead6-c365-4dec-86a4-82a71b972ee9",
            "sourceColumn": "char_attr_img",
            "summarizeBy": "none"
          },
          {
            "name": "char_attr_txt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cb60e89-56a4-4dba-8628-cbed6176b1a4",
            "sourceColumn": "char_attr_txt",
            "summarizeBy": "none"
          },
          {
            "name": "char_blurb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "306d6fe9-ec03-4773-8ec6-6539ee5e0c34",
            "sourceColumn": "char_blurb",
            "summarizeBy": "none"
          },
          {
            "name": "char_history",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e779346-a2cc-46b4-862e-90a94388c863",
            "sourceColumn": "char_history",
            "summarizeBy": "none"
          },
          {
            "name": "char_type_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57a088c9-c2b2-4b4d-b6f6-ca47634b8e36",
            "sourceColumn": "char_type_img",
            "summarizeBy": "none"
          },
          {
            "name": "char_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d723989f-a4ab-4388-9d62-506eff6f2269",
            "sourceColumn": "char_type",
            "summarizeBy": "none"
          },
          {
            "name": "char_attr_img_html",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6bcad6b-b4fa-4779-ad7e-5df3ec19fa61",
            "sourceColumn": "char_attr_img_html",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "334d1788-d0a1-4a5f-b9e1-9908de85ef08",
        "partitions": [
          {
            "name": "hero_scrape",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1JhQDKRX0o7GZH9CVEuSj8-r1oNx2XGYzfaTVH3tkCDI/edit?usp=sharing\"),",
                "    hero_scrape_Table = Source{[name=\"hero_scrape\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(hero_scrape_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"abil1title\", type text}, {\"abil1text\", type text}, {\"abil1img\", type text}, {\"abil1vid\", type text}, {\"abil2title\", type text}, {\"abil2text\", type text}, {\"abil2img\", type text}, {\"abil2vid\", type text}, {\"abil3title\", type text}, {\"abil3text\", type text}, {\"abil3img\", type text}, {\"abil3vid\", type text}, {\"abil4title\", type text}, {\"abil4text\", type text}, {\"abil4img\", type text}, {\"abil4vid\", type text}, {\"char_attr_img\", type text}, {\"char_attr_txt\", type text}, {\"char_name\", type text}, {\"char_blurb\", type text}, {\"char_history\", type text}, {\"char_type_img\", type text}, {\"char_type\", type text}, {\"abil5title\", type text}, {\"abil5text\", type text}, {\"abil5img\", type text}, {\"abil5vid\", type text}, {\"abil6title\", type text}, {\"abil6text\", type text}, {\"abil6img\", type text}, {\"abil6vid\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"abil1text\", \"abil1img\", \"abil1vid\", \"abil2title\", \"abil2text\", \"abil2img\", \"abil2vid\", \"abil3title\", \"abil3text\", \"abil3img\", \"abil3vid\", \"abil4title\", \"abil4text\", \"abil4img\", \"abil4vid\", \"abil5img\", \"abil5vid\", \"abil6title\", \"abil6text\", \"abil6img\", \"abil6vid\", \"abil5title\", \"abil5text\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Removed Columns\",{\"char_name\", \"abil1title\", \"char_attr_img\", \"char_attr_txt\", \"char_blurb\", \"char_history\", \"char_type_img\", \"char_type\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns\",{\"abil1title\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Characters 2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "names",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3da085ea-ad1c-4af8-9de4-a676b076764f",
            "sourceColumn": "names",
            "summarizeBy": "none"
          },
          {
            "name": "button_images",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02f024fa-bce5-40fa-950b-450110e0e29a",
            "sourceColumn": "button_images",
            "summarizeBy": "none"
          },
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a62f890-b5d5-45a2-b9ac-99d25837599d",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "name_caps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06a7f637-5e8f-4cf5-a295-238d9f644057",
            "sourceColumn": "name_caps",
            "summarizeBy": "none"
          },
          {
            "name": "video_resized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f4ae41e-46a1-4bf3-8212-8a7577542b98",
            "sourceColumn": "video_resized",
            "summarizeBy": "none"
          },
          {
            "name": "ability_1_img",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35699565-ebbf-45c0-ae87-50b4a17c3fa6",
            "sourceColumn": "ability_1_img",
            "summarizeBy": "none"
          },
          {
            "name": "ability_1_vid_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec83d2b3-d121-420a-93dc-20a157302290",
            "sourceColumn": "ability_1_vid_code",
            "summarizeBy": "none"
          },
          {
            "name": "ab1_title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1541c68-5250-4ff3-b525-8530561707c5",
            "sourceColumn": "ab1_title",
            "summarizeBy": "none"
          },
          {
            "name": "_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eb680e8-77ab-4eec-8777-e490d723c4fb",
            "sourceColumn": "_2",
            "summarizeBy": "none"
          },
          {
            "name": "_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f664b893-71b1-42ca-bac4-72a32b8958eb",
            "sourceColumn": "_3",
            "summarizeBy": "none"
          },
          {
            "name": "_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed0eba18-905c-4ac7-923b-c12e6dd54418",
            "sourceColumn": "_4",
            "summarizeBy": "none"
          },
          {
            "name": "_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e698c20-515c-48b3-9bef-2836b7b95c40",
            "sourceColumn": "_5",
            "summarizeBy": "none"
          },
          {
            "name": "_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3136a517-c8ed-4ad6-9c9b-ad51576bdaa1",
            "sourceColumn": "_6",
            "summarizeBy": "none"
          },
          {
            "name": "_7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63449b20-73ed-4ddc-bd44-0901229d5759",
            "sourceColumn": "_7",
            "summarizeBy": "none"
          },
          {
            "name": "_8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c5a3653-edcf-48ec-962c-9accfd3c22b7",
            "sourceColumn": "_8",
            "summarizeBy": "none"
          },
          {
            "name": "_9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e73658bf-200c-41b3-870b-850de44fbb59",
            "sourceColumn": "_9",
            "summarizeBy": "none"
          },
          {
            "name": "_10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df23d19f-dd52-444d-a9f0-36eb6039cd8f",
            "sourceColumn": "_10",
            "summarizeBy": "none"
          },
          {
            "name": "_11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c74aa423-87e0-47d0-b29d-00da4d9aa0e7",
            "sourceColumn": "_11",
            "summarizeBy": "none"
          },
          {
            "name": "_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39229a06-ef58-4d71-89bf-752d4737eaea",
            "sourceColumn": "_12",
            "summarizeBy": "none"
          },
          {
            "name": "_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82602d58-b696-4d4e-8926-041a1c67f442",
            "sourceColumn": "_13",
            "summarizeBy": "none"
          },
          {
            "name": "_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5127d411-c429-4888-b0e4-8bae4c24b727",
            "sourceColumn": "_14",
            "summarizeBy": "none"
          },
          {
            "name": "_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed63a97e-5d93-465a-b5ce-6ce557390da8",
            "sourceColumn": "_15",
            "summarizeBy": "none"
          },
          {
            "name": "_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a7c6352-a784-4896-ba0a-73e972b5f0b3",
            "sourceColumn": "_16",
            "summarizeBy": "none"
          },
          {
            "name": "_17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "745835d8-f0e3-4a04-9e46-16b4f3f71292",
            "sourceColumn": "_17",
            "summarizeBy": "none"
          },
          {
            "name": "_18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f79c3e46-c45d-45ee-9350-864df1849321",
            "sourceColumn": "_18",
            "summarizeBy": "none"
          },
          {
            "name": "_19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ee946ae-43c5-49cb-9fc2-c060dd2e8d72",
            "sourceColumn": "_19",
            "summarizeBy": "none"
          },
          {
            "name": "_20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "614996a6-d9fe-4c6d-81c0-441860373b73",
            "sourceColumn": "_20",
            "summarizeBy": "none"
          },
          {
            "name": "_21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce3bc096-871a-4d18-88ef-35258977771a",
            "sourceColumn": "_21",
            "summarizeBy": "none"
          },
          {
            "name": "_22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0a45c6f-f279-4c71-bda5-473c40acf073",
            "sourceColumn": "_22",
            "summarizeBy": "none"
          },
          {
            "name": "_23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a0da77f-4d03-4ff7-93f6-192262302df5",
            "sourceColumn": "_23",
            "summarizeBy": "none"
          },
          {
            "name": "_24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cb81a33-8fe6-4d4c-91af-33b9d4497cfb",
            "sourceColumn": "_24",
            "summarizeBy": "none"
          },
          {
            "name": "_25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5c303f5-4da1-454b-b157-96787a445d7a",
            "sourceColumn": "_25",
            "summarizeBy": "none"
          },
          {
            "name": "_26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0fed850-2799-44fc-a7ad-47df26427b39",
            "sourceColumn": "_26",
            "summarizeBy": "none"
          },
          {
            "name": "_27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88e23f1b-7f1b-44a9-8434-1abd65c0eef9",
            "sourceColumn": "_27",
            "summarizeBy": "none"
          },
          {
            "name": "_28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85d0cf40-fec8-4582-92e1-0e5bf4847ca7",
            "sourceColumn": "_28",
            "summarizeBy": "none"
          },
          {
            "name": "_29",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f383df59-37dd-4191-a6aa-aadbd3676b70",
            "sourceColumn": "_29",
            "summarizeBy": "none"
          },
          {
            "name": "_30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6e05fc4-2b8d-4c70-a811-f8bea7616740",
            "sourceColumn": "_30",
            "summarizeBy": "none"
          },
          {
            "name": "_31",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d699aeeb-d4de-4580-a026-633b5605e12d",
            "sourceColumn": "_31",
            "summarizeBy": "none"
          },
          {
            "name": "_32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfc48718-1a4b-4925-b028-af159c1112b2",
            "sourceColumn": "_32",
            "summarizeBy": "none"
          },
          {
            "name": "_33",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12dec830-45f4-4946-903e-95039ad0bbc2",
            "sourceColumn": "_33",
            "summarizeBy": "none"
          },
          {
            "name": "_34",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fab1ae5a-7489-46c7-94d2-05cdae069dea",
            "sourceColumn": "_34",
            "summarizeBy": "none"
          },
          {
            "name": "_35",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c0491ea-5fdf-45f3-855e-0a3eb1bebb30",
            "sourceColumn": "_35",
            "summarizeBy": "none"
          },
          {
            "name": "_36",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51efba2d-e76d-4bb8-925e-a3b8e93c20de",
            "sourceColumn": "_36",
            "summarizeBy": "none"
          },
          {
            "name": "_37",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6498aca-38a9-4e4e-bd97-e863f8c02431",
            "sourceColumn": "_37",
            "summarizeBy": "none"
          },
          {
            "name": "_38",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4851b592-b54b-4bb8-93c2-9088ce30446a",
            "sourceColumn": "_38",
            "summarizeBy": "none"
          },
          {
            "name": "_39",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4de0ab5-975f-4b92-8737-0a22119ca64c",
            "sourceColumn": "_39",
            "summarizeBy": "none"
          },
          {
            "name": "_40",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d6d2b99-0aaf-4654-ad27-6ac85a5312e2",
            "sourceColumn": "_40",
            "summarizeBy": "none"
          },
          {
            "name": "_41",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23b1bc6c-b4b1-4134-968c-f8a0c195d9c1",
            "sourceColumn": "_41",
            "summarizeBy": "none"
          },
          {
            "name": "_42",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b9090c8-d7f1-4469-bf0d-9129faf56124",
            "sourceColumn": "_42",
            "summarizeBy": "none"
          },
          {
            "name": "_43",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39889ec2-9a4a-488d-8fee-8cc006fc78e4",
            "sourceColumn": "_43",
            "summarizeBy": "none"
          },
          {
            "name": "_44",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "141f700f-240e-49d9-af75-d8c52ea7cff4",
            "sourceColumn": "_44",
            "summarizeBy": "none"
          },
          {
            "name": "_45",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98fa6074-0aaf-4224-ac20-cbb4fcef7614",
            "sourceColumn": "_45",
            "summarizeBy": "none"
          },
          {
            "name": "_46",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86093421-e96f-4d20-97e1-861ab899cb2f",
            "sourceColumn": "_46",
            "summarizeBy": "none"
          },
          {
            "name": "_47",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28ee2a66-14a1-4e79-9504-7249f0075419",
            "sourceColumn": "_47",
            "summarizeBy": "none"
          },
          {
            "name": "_48",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c9c2b79-1b44-47c9-b5c1-c2c70de1ed5d",
            "sourceColumn": "_48",
            "summarizeBy": "none"
          },
          {
            "name": "_49",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0032b3f-0ae3-4639-a213-4db1432ff2f6",
            "sourceColumn": "_49",
            "summarizeBy": "none"
          },
          {
            "name": "_50",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec978307-ccba-4460-a745-8e5b0bf105c4",
            "sourceColumn": "_50",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b9f6907e-b789-415f-a922-eec94bcaf52a",
        "measures": [
          {
            "name": "h2h vid",
            "expression": "CALCULATE(MAX('Characters 2'[video_resized]), ALL(Characters), USERELATIONSHIP('Characters 2'[names], heroes_powerbi[localized_name]))",
            "lineageTag": "c04cb1e9-b0b4-4962-97e4-e2582122f965"
          }
        ],
        "partitions": [
          {
            "name": "Characters 2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1zLxE1yP648A_V_HPK0kZu2wDrG2vRDaf4A3UJzb9RPk/edit?usp=sharing\"),",
                "    Characters_Table = Source{[name=\"Characters\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Characters_Table, [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"ability_1_class_start\", \"ability_1_img_start\", \"ability_1_img_end\", \"ability_1_video_html_start\", \"ability_1_video_html_start_1\", \"ab1_class_start\", \"ab1_text_start\", \"\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "players_final_items",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "match_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce4ea381-f53e-44b1-b509-5e56f8c5c596",
            "sourceColumn": "match_id",
            "summarizeBy": "sum"
          },
          {
            "name": "account_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a6ff2cc8-1e44-46d3-9c61-726667c601b0",
            "sourceColumn": "account_id",
            "summarizeBy": "sum"
          },
          {
            "name": "item_slot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb9cc618-4c70-4593-9d1f-5b58d11ab3da",
            "sourceColumn": "item_slot",
            "summarizeBy": "sum"
          },
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f872e40c-5b29-4b1e-bde8-b8d710441561",
            "sourceColumn": "item",
            "summarizeBy": "none"
          },
          {
            "name": "primary_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b7763a2-e366-4672-a97a-f5a408a93530",
            "sourceColumn": "primary_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d3eb68b2-ef20-4359-b14d-2f942bdedae4",
        "partitions": [
          {
            "name": "players_final_items",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleBigQuery.Database(),",
                "    #\"dota-2-77927\" = Source{[Name=\"dota-2-77927\"]}[Data],",
                "    dota2_Schema = #\"dota-2-77927\"{[Name=\"dota2\",Kind=\"Schema\"]}[Data],",
                "    players_final_items_Table = dota2_Schema{[Name=\"players_final_items\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(players_final_items_Table,{{\"account_id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}